import type { Metadata } from "next";
import "./globals.css";
import { Container } from "../components/Container";
import { Header } from "../components/Header";
import clsx from "clsx";
import { Footer } from "../components/Footer";

export const metadata: Metadata = {
  title: {
    default: "The Blog - Este é um blog com Next.js",
    template: '%s | The Blog'
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>
        <Container>
          <Header />

          {children}

          <Footer/>
        </Container>
      </body>
    </html>
  );
}
